# Generated by Django 5.1 on 2024-09-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domanda', models.CharField(blank=True, max_length=255)),
                ('Risposta', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
