# Generated by Django 5.1 on 2024-09-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Budgeting', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SfidaFamigliare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusa', models.BooleanField(default=False)),
                ('durata', models.CharField(max_length=20)),
                ('data_creazione', models.DateField()),
                ('data_accettazione', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField()),
                ('importo_sfidante', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importo_sfidato', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descrizione', models.TextField()),
                ('sfidante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfidante', to='Users.utente')),
                ('sfidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sfidato', to='Users.utente')),
                ('vincitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vincitore', to='Users.utente')),
            ],
        ),
        migrations.CreateModel(
            name='SfidaPersonale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sfida', models.CharField(max_length=50)),
                ('conclusa', models.BooleanField(default=False)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descrizione', models.TextField()),
                ('premio', models.IntegerField()),
                ('data_scadenza', models.DateField()),
                ('data_creazione', models.DateField()),
                ('data_avvio', models.DateField(blank=True, null=True)),
                ('categoria_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budgeting.categoriaspesa')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.utente')),
            ],
        ),
    ]
