# Generated by Django 5.1 on 2024-10-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfidafamigliare',
            name='data_accettazione',
        ),
    ]
