# Generated by Django 5.1 on 2024-10-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0012_alter_obbiettivospesa_tipo'),
        ('Challenges', '0002_remove_sfidafamigliare_data_accettazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfidafamigliare',
            name='categoria_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Budgeting.categoriaspesa'),
        ),
    ]
