# Generated by Django 5.1 on 2024-10-11 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0003_sfidafamigliare_categoria_target'),
        ('Users', '0006_remove_utente_famiglia_utente_famiglia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfidafamigliare',
            name='famiglia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.famiglia'),
        ),
    ]
