# Generated by Django 5.1 on 2024-10-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0005_alter_sfidafamigliare_famiglia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfidafamigliare',
            name='durata',
        ),
    ]
