# Generated by Django 5.1 on 2024-10-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0006_remove_sfidafamigliare_durata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfidafamigliare',
            name='descrizione',
            field=models.TextField(null=True),
        ),
    ]
