# Generated by Django 5.1 on 2024-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0007_alter_sfidafamigliare_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfidafamigliare',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
