# Generated by Django 5.1 on 2024-10-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0009_sfidafamigliare_percentuale_sfidante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfidafamigliare',
            name='percentuale_sfidante',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sfidafamigliare',
            name='percentuale_sfidato',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
    ]
