# Generated by Django 5.1 on 2024-09-24 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Budgeting', '0001_initial'),
        ('Challenges', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('provenienza', models.CharField(max_length=50)),
                ('data_notifica', models.DateField()),
                ('letta', models.BooleanField(default=False)),
                ('data_lettura', models.DateField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.utente')),
            ],
        ),
        migrations.CreateModel(
            name='NotificaFamiglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('id_notifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.notifica')),
                ('rif_sfida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenges.sfidafamigliare')),
                ('rif_transazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budgeting.transazione')),
            ],
            options={
                'unique_together': {('id_notifica',)},
            },
        ),
        migrations.CreateModel(
            name='NotificaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('id_notifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.notifica')),
                ('rif_obbiettivo_spesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budgeting.obbiettivospesa')),
                ('rif_piano_risparmio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budgeting.pianodirisparmio')),
                ('rif_sfida_personale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Challenges.sfidapersonale')),
            ],
            options={
                'unique_together': {('id_notifica',)},
            },
        ),
    ]
