# Generated by Django 5.1 on 2024-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_saldototale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldototale',
            name='data_aggiornamento',
            field=models.DateField(),
        ),
    ]
