# Generated by Django 5.1 on 2024-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_saldototale_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conto',
            name='tipo',
            field=models.CharField(choices=[('corrente', 'Checking Account'), ('investimento', 'Investment Account'), ('risparmio', 'Savings Account'), ('contante', 'Cash')], default='corrente', max_length=20),
        ),
    ]
