# Generated by Django 5.1 on 2024-10-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_conto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conto',
            name='condiviso',
            field=models.BooleanField(default=False),
        ),
    ]
