# Generated by Django 5.1 on 2024-10-14 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_conto_condiviso'),
        ('Users', '0006_remove_utente_famiglia_utente_famiglia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoTotaleInvestimenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_totale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_aggiornamento', models.DateField()),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.utente')),
            ],
        ),
    ]
