# Generated by Django 5.1 on 2024-10-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_posizioneaperta'),
    ]

    operations = [
        migrations.AddField(
            model_name='posizioneaperta',
            name='numero_azioni',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
