# Generated by Django 5.1 on 2024-10-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_conto_liquidita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conto',
            name='liquidita',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0, max_digits=10), max_digits=10),
        ),
    ]
