# Generated by Django 5.1 on 2024-09-24 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObbiettivoSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentuale_completamento', models.FloatField(default=0)),
                ('tipo', models.CharField(max_length=20)),
                ('data_scadenza', models.DateField()),
                ('data_creazione', models.DateField()),
                ('categoria_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budgeting.categoriaspesa')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.utente')),
            ],
        ),
        migrations.CreateModel(
            name='PianoDiRisparmio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durata', models.CharField(max_length=20)),
                ('obbiettivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_scadenza', models.DateField()),
                ('data_creazione', models.DateField()),
                ('conto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.conto')),
            ],
        ),
        migrations.CreateModel(
            name='SottoCategoriaSpesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalizzata', models.BooleanField(default=False)),
                ('data_creazione', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('categoria_superiore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Budgeting.categoriaspesa')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('mostra', models.BooleanField(default=True)),
                ('tipo_transazione', models.CharField(choices=[('delegata', 'Transazione Delegata'), ('singola', 'Transazione Singola'), ('periodica', 'Transazione Periodica'), ('futura', 'Transazione Futura'), ('trasferimento', 'Trasferimento tra Conti'), ('investimento', 'Transazione di Investimento')], default='singola', max_length=20)),
                ('prossimo_rinnovo', models.DateField(blank=True, null=True)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('prezzo_azione', models.FloatField(blank=True, null=True)),
                ('numero_azioni', models.FloatField(blank=True, null=True)),
                ('borsa', models.CharField(blank=True, max_length=50, null=True)),
                ('valuta', models.CharField(blank=True, max_length=3, null=True)),
                ('accetta_delega', models.BooleanField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('tipo_rinnovo', models.CharField(choices=[('settimanale', 'Rinnovo Settimanale'), ('mensile', 'Rinnovo Mensile'), ('semestrale', 'Rinnovo Semestrale')], default='mensile', max_length=20)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Budgeting.categoriaspesa')),
                ('conto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.conto')),
                ('mittente_delega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegante', to='Users.utente')),
                ('sotto_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Budgeting.sottocategoriaspesa')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.utente')),
            ],
        ),
    ]
