# Generated by Django 5.1 on 2024-09-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottocategoriaspesa',
            name='utente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.utente'),
        ),
        migrations.AlterField(
            model_name='transazione',
            name='tipo_rinnovo',
            field=models.CharField(choices=[('settimanale', 'Rinnovo Settimanale'), ('mensile', 'Rinnovo Mensile'), ('semestrale', 'Rinnovo Semestrale')], default='mensile', max_length=20, null=True),
        ),
    ]
