# Generated by Django 5.1 on 2024-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0002_alter_sottocategoriaspesa_utente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transazione',
            name='tipo_rinnovo',
            field=models.CharField(choices=[('settimanale', 'Rinnovo Settimanale'), ('mensile', 'Rinnovo Mensile'), ('semestrale', 'Rinnovo Semestrale'), ('nessuno', 'Nessun Rinnovo')], default='nessuno', max_length=20),
        ),
    ]
