# Generated by Django 5.1 on 2024-10-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_conto_nome'),
        ('Budgeting', '0005_transazione_eseguita'),
    ]

    operations = [
        migrations.AddField(
            model_name='transazione',
            name='conto_arrivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conto_arrivo', to='Accounts.conto'),
        ),
        migrations.AlterField(
            model_name='transazione',
            name='conto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conto_partenza', to='Accounts.conto'),
        ),
    ]
