# Generated by Django 5.1 on 2024-10-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0006_transazione_conto_arrivo_alter_transazione_conto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pianodirisparmio',
            name='percentuale_completamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
