# Generated by Django 5.1 on 2024-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0007_pianodirisparmio_percentuale_completamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obbiettivospesa',
            name='data_creazione',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='obbiettivospesa',
            name='tipo',
            field=models.CharField(choices=[('mensile', 'Mensile'), ('trimestrale', 'Trimestrale'), ('semestrale', 'Semestrale'), ('annuale', 'Annuale')], max_length=20),
        ),
    ]
