# Generated by Django 5.1 on 2024-10-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0008_alter_obbiettivospesa_data_creazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obbiettivospesa',
            name='importo_speso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
