# Generated by Django 5.1 on 2024-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0010_alter_transazione_tipo_rinnovo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transazione',
            name='tipo_rinnovo',
            field=models.CharField(blank=True, choices=[('settimanale', 'Weekly Renewal'), ('mensile', 'Monthly Renewal'), ('semestrale', 'Semi-Annual Renewal')], default=None, max_length=20, null=True),
        ),
    ]
