# Generated by Django 5.1 on 2024-10-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0012_alter_obbiettivospesa_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transazione',
            name='accetta_delega',
        ),
        migrations.RemoveField(
            model_name='transazione',
            name='borsa',
        ),
        migrations.RemoveField(
            model_name='transazione',
            name='valuta',
        ),
        migrations.AlterField(
            model_name='transazione',
            name='tipo_transazione',
            field=models.CharField(choices=[('singola', 'Single Transaction'), ('periodica', 'Recurring Transaction'), ('futura', 'Future Transaction'), ('trasferimento', 'Account Transfer'), ('investimento', 'Investment Transaction')], default='singola', max_length=20),
        ),
    ]
