# Generated by Django 5.1 on 2024-10-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgeting', '0013_remove_transazione_accetta_delega_and_more'),
        ('Users', '0006_remove_utente_famiglia_utente_famiglia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sottocategoriaspesa',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.utente'),
        ),
    ]
