# Generated by Django 5.1 on 2024-08-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='descrizione',
            field=models.CharField(default='Null', max_length=150),
            preserve_default=False,
        ),
    ]
