# Generated by Django 5.1 on 2024-09-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famiglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partecipanti', models.IntegerField(default=1)),
                ('nome_famiglia', models.CharField(max_length=50)),
                ('data_creazione', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_di_nascita', models.DateField()),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=10)),
                ('sesso', models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina'), ('O', 'Altro')], default='M', max_length=1)),
                ('monete_account', models.IntegerField(default=0)),
                ('data_registrazione', models.DateField()),
                ('famiglia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.famiglia')),
            ],
        ),
    ]
