# Generated by Django 5.1 on 2024-10-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_utente_sesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='famiglia',
            name='codice',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
