# Generated by Django 5.1 on 2024-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_famiglia_codice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='famiglia',
        ),
        migrations.AddField(
            model_name='utente',
            name='famiglia',
            field=models.ManyToManyField(blank=True, to='Users.famiglia'),
        ),
    ]
