# Generated by Django 5.1 on 2024-09-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percorso_risorsa', models.CharField(blank=True, max_length=255, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AcquistoPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.utente')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reward.premio')),
            ],
            options={
                'unique_together': {('premio', 'utente')},
            },
        ),
    ]
