# Generated by Django 5.1 on 2024-10-17 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acquistopremio',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='premio',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='percorso_risorsa',
        ),
        migrations.AddField(
            model_name='acquistopremio',
            name='data_acquisto',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='premio',
            name='costo_monete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premio',
            name='valore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
